baseURL: 'https://rizin.re/'
title: Rizin
paginate: 10
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
      - name: Blog
        url: /posts/
        weight: 5
      - name: Organization
        url: /organization/
        weight: 10
      - name: Cutter
        url: https://cutter.re
        weight: 15
      - name: Search
        url: /search/
        weight: 15

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rizin
  description: 'Rizin is a free and Open Source Reverse Engineering Framework'
  author: Rizin
  images:
    - /images/rizin_preview.png
  
  header:
    title: 'rizin'
    imageUrl: '/images/rizin.svg'
    subtitle: 'Free and Open Source Reverse Engineering Framework'

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  # dark, light, auto
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/rizinorg'
    - name: github
      url: 'https://github.com/rizinorg'

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary